### ISSUE TITLE
Error on PTS for Update 40

### ISSUE THREAD

**Issue by Navarill** [sirinsidiator/ESO-LibNotification#1]
When mouse-over Daily Reward (only thing in my Notifications), immediately triggers lua error every time. Disabled all addons, problem goes away. Enabled PTS version of Addon Selector = no problem yet. Enabled LibNotification = problem returns. On every mouse-over of the checkmark next to the Daily Reward notification. NOTIFICATIONS seems to be nil when the error happens. Please see https://sir.insidi.at/or/logviewer/Z3OFlT for the error. I have not seen this on live - only the current PTS.

**Comment by sirinsidiator** [comment]
Should be fixed. Thanks for the report!
